// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6UVcBT4uweb49-4iu0u7oOWtJ1gIBKxY',
    appId: '1:960377348627:web:0c67dc81f4cdfb9c9d15e6',
    messagingSenderId: '960377348627',
    projectId: 'ticktok-c67f5',
    authDomain: 'ticktok-c67f5.firebaseapp.com',
    storageBucket: 'ticktok-c67f5.appspot.com',
    measurementId: 'G-1LW984V8JR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCWYyYFpQBd0CSzGnmON_G66CUMiwhc0M',
    appId: '1:960377348627:android:0b39fa691f010a9d9d15e6',
    messagingSenderId: '960377348627',
    projectId: 'ticktok-c67f5',
    storageBucket: 'ticktok-c67f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL3tM37xwHBweqjtWnSNB-E2HLl-Lj74U',
    appId: '1:960377348627:ios:af1dea0d673cd2159d15e6',
    messagingSenderId: '960377348627',
    projectId: 'ticktok-c67f5',
    storageBucket: 'ticktok-c67f5.appspot.com',
    iosClientId:
        '960377348627-26cuu29qj3tj8mrn2ipi0b219kjhvjth.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL3tM37xwHBweqjtWnSNB-E2HLl-Lj74U',
    appId: '1:960377348627:ios:af1dea0d673cd2159d15e6',
    messagingSenderId: '960377348627',
    projectId: 'ticktok-c67f5',
    storageBucket: 'ticktok-c67f5.appspot.com',
    iosClientId:
        '960377348627-26cuu29qj3tj8mrn2ipi0b219kjhvjth.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktok',
  );
}
